### ISSUE TITLE
Balances() not working, returning [InvalidSignature] error

### ISSUE THREAD

**Issue by wang502** [jsgoyette/gemini#1]
It seems the current implementation of `func Balances() ([]FundBalance, error)` in routes-private.go does not follow the official documentation of Gemini private api authentication, which can be found here: https://docs.gemini.com/rest-api/#private-api-invocation . 
As a result, every time I call this method, an `InvalidSignature` error is returned.

**Comment by jsgoyette** [comment]
This error is likely because you are using sandbox api keys in live mode, or using live api keys in sandbox mode. If you want to use it in live mode, then you should set the first argument of `gemini.New()` to true, otherwise for sandbox mode set it to false.

If you need to generate sandbox api keys, go to https://sandbox.gemini.com/

**Comment by wang502** [comment]
Thank you for help. 
More context: I am using live API key and I also have set the live mode to be true.  Do you still think the reason is because using sandbox api keys in live mode?

**Comment by jsgoyette** [comment]
Hmm, that doesn't sound like it then.

My next best guess is to ask, does your key/secret pair have the Fund Managenent role? It's not checked by default when creating a new key pair and easily could be missed, and it's required for checking balances.

**Comment by wang502** [comment]
The latest key pair I generated has fund management included. Probably not because of this.

**Comment by jsgoyette** [comment]
If you check out the `BuildHeader` function starting on line 231 of gemini.go, you'll see that the header includes the key, payload and signature as per spec. The request is made in `request` function that follows, and in there I encourage you to add `fmt.Printf("%+v", req.Header)` to line 271 to confirm that the headers are getting set correctly.

I'm not sure what issue you are running into, though I highly doubt it's due to something as egregious as a malformed api request. I use this code daily and update my scripts and recompile all the time. The only way I can recreate an InvalidSignature error is if I do something wrong with the keys, like pass them incorrectly to the `New` function or have invalid keys with insufficient access privileges.

Since I am unable to recreate the issue, could you provide more context, like a code snippet that reproduces the problem?
